Repository PrestaShopCorp/ps_eventbus, pull requests merged in 2023-04, with the labels that each got.

#160 eb-414 add lint/file/repository
  config/front/repository.yml
  config/front/services.yml
  src/Repository/SpecificPriceRepository.php
  src/Service/SpecificPriceService.php
  tests/unit/Decorator/PayloadDecoratorTest.php
  tests/unit/Formatter/ArrayFormatterTest.php
  tests/unit/Formatter/JsonFormatterTest.php
Labels: 🥕 Radis to review

#161 Feat/eb 682 add synctype eventbus
  src/Controller/AbstractApiController.php
Labels: 🥕 Radis to review

#162 Feat/stores
  config/front/decorator.yml
  config/front/provider.yml
  config/front/repository.yml
  controllers/front/apiStores.php
  ps_eventbus.php
  src/Config/Config.php
  src/Decorator/StoreDecorator.php
  src/Provider/CartDataProvider.php
  src/Provider/StoreDataProvider.php
  src/Repository/StoreRepository.php
  tests/System/Tests/Synchronization/FullSynchronizationTest.php
  tests/System/Tests/Synchronization/IncrementalSynchronizationTest.php
  upgrade/Upgrade-1.10.7.php
Labels: Feature, 🥕 Radis to review

#163 Feat EB-729
  src/Service/PresenterService.php
Labels: 🥕 Radis to review

#164 Feat/stocks
  config/front/decorator.yml
  config/front/provider.yml
  config/front/repository.yml
  controllers/front/apiStocks.php
  ps_eventbus.php
  src/Config/Config.php
  src/Decorator/StockDecorator.php
  src/Provider/StockDataProvider.php
  src/Repository/CurrencyRepository.php
  src/Repository/StockMvtRepository.php
  src/Repository/StockRepository.php
  upgrade/Upgrade-1.10.8.php
Labels: Feature, 🥕 Radis to review

#165 Fix/order cart rules deleted
  src/Provider/OrderDataProvider.php
  src/Repository/OrderCartRuleRepository.php
Labels: 🐛 Bug, 🥕 Radis to review
